#!/usr/bin/env python

#Select a random set of characters
import random 

#Create a list of characters to generate a password from
chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*"

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--number", type=int, default=1, help="amount of passwords to generate")
parser.add_argument("--length", type=int, default=16, help="length of the password to generate")
args = parser.parse_args()
number = args.number
length = args.length
number = args.number

for p in range(number):
    password = " "
    for c in range(length):
        password += random.choice(chars)
    print(password)
